### ISSUE TITLE
result.block.header.number is a compact integer

### ISSUE THREAD

**Issue by amaury1093** [mxinden/test-engineer-take-home-task#2]
@mxinden I just thought of a hidden problem in the task

```
curl ...
jq \
        .result.block.header.number
```

This will give a number like `0x0627`. However, it's not a simple byte-by-byte encoding as one might initially think, but SCALE-encoded (and it's a compact integer).

As-is, I think that most candidates will scratch their head for a long time before they realize that the hex has a special encoding.

Solutions:
- In the hint, give a link to SCALE encoding, in particular how to decode compact integers. We could give 1/ the web3 paper (I can't find the link though) and 2/ the source codes (JS & Rust).
- In the hint, propose them to use the PolkadotJS api, which does the decoding internally.
- We could even say: "wait until the block number shows `0x0485`. This is the scale-encoded value of 1234, read here to learn more about scale" (_note: 0x0485 is totally random_)

**Comment by amaury1093** [comment]
Actually, probably false alert. For small integers, SCALE and byte-to-byte encoding are the same.  Block 10 gives `0xa`.

Although I think we should still talk about SCALE.

**Comment by mxinden** [comment]
Great catch @amaurymartiny. I will prepare a pull request to add a note to the document.
